spring:
  profiles:
    active : production
---
#server configuration
spring:
  profiles: production

server:
   port: 80
   address: 64.137.215.246
---
#local postgres configuration
spring:
  profiles: local

server:
  port: 8080
  address: localhost
---
# Database
db:
  driver: org.postgresql.Driver
  link: jdbc:postgresql://localhost:5432/colette
  username: postgres
  password: postgres

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  format_sql: true
  use_sql_comments: true
  hbm2ddl.auto: false

entitymanager:
  packagesToScan: com.newsua
